# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix

      ./custom.nix
      ../common/virtualisation/podman.nix
    ];

  users.users.nixos = {
    uid = 502;
    extraGroups = [ "wheel" "orbstack" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/nixos";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Bangkok";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIIBwDCCAWegAwIBAgIRAIdNrwmRDwavRMiZcWe1hIEwCgYIKoZIzj0EAwIwMzEx
MC8GA1UEAxMoQ2FkZHkgTG9jYWwgQXV0aG9yaXR5IC0gRUNDIEludGVybWVkaWF0
ZTAeFw0yNDA2MjIwMjIzMDFaFw0yNDA2MjIxNDIzMDFaMAAwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAASxG6RZr3nWAycvZxnk7SQqU74MVPvXd4Is+8/2HZ9cefs1
9V0z6soj/fCe0law7tkaFjI0ghe5UenpRjZAcuFEo4GOMIGLMA4GA1UdDwEB/wQE
AwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFMT3
+W+u5LOTo2WWO91+iVn4w4NgMB8GA1UdIwQYMBaAFHQdqUm+o9r6kGBaZVPSfBJb
xGpBMBoGA1UdEQEB/wQQMA6CDG5hcmExNy5sb2NhbDAKBggqhkjOPQQDAgNHADBE
AiBY0PZeU0P9BYMwTjO0qtoygPJalS7Pgt3qbL+klHE+JQIgZmYc2osIM08lFHSZ
RI6pxytEIiEmwqegu6Xx/xmLveU=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIDKDCCAhCgAwIBAgIRAOgLE3wM2B7+TiaWNChxKxcwDQYJKoZIhvcNAQELBQAw
PTELMAkGA1UEBhMCRU4xEDAOBgNVBAoMB0FkR3VhcmQxHDAaBgNVBAMME0FkZ3Vh
cmQgUGVyc29uYWwgQ0EwHhcNMjMxMDE4MTIyMDA1WhcNNDMxMDEzMTIyMDA1WjA9
MQswCQYDVQQGEwJFTjEQMA4GA1UECgwHQWRHdWFyZDEcMBoGA1UEAwwTQWRndWFy
ZCBQZXJzb25hbCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANkG
r/P2AozCczp0yk4xVpw/Fiha5nYTqSezA0chXOFRLtlMMH7pCjyAHuub4wfxsUQ4
O5xQ0IhnxwTd3B3NeGOe++Gb8vyc0bF4DwAzeYZrpTdR6FfisGPm2PhV3nH1Y80K
n7OiWpMeUCkJst4lWPnNBJ7ZiWzIib+z6LDro2pfSZuGq8aqVY4b2WW1dn3MyLdx
8gMYdxpHD35+QilcT4zzu/vBm9hXVZPrdlBg3MXe2cvubC3eSLnBNARIt9kDVv9V
oZ7HmudAjUEM8qgvWBhG92RIFebHzNr3sSpvOI8lpbF5eQchxqj4tUKj1LbanEKn
W4la60BlNiHMv5hISjkCAwEAAaMjMCEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8B
Af8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBALe5gkU3wLg4/sc8dakW+ZQ1F9Sn
lZ/lcBUfHcR1T5CO6QaMcya4uHk9CbnbmP+ov1ybpyOTe/bjAm9twhWcYQSI8bQ1
mSLgD+XzvkGL8c3R8EzCOxkUF63VzY+ZSunt/QL8My8p6gnQ+fHC5Cpc4JV1w01H
pjdhsbk4cnmbwXUcpoU47/T/JGZ2q+sOeQy/6HbdD8JCnkawaGMzyQtxsgjRyQQn
X9QcZGGWuG21TXus0b4xP0OeprXes6QFx/YUaGugujHTfmiDbFiS96x//Jv0mnGg
5yA5BZYZ8vg5UHSa2zGcfPgBLANGfg5ZyLJNEcm9PJYqmmZSSCb/6lXhB44=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIBwDCCAWegAwIBAgIRAIdNrwmRDwavRMiZcWe1hIEwCgYIKoZIzj0EAwIwMzEx
MC8GA1UEAxMoQ2FkZHkgTG9jYWwgQXV0aG9yaXR5IC0gRUNDIEludGVybWVkaWF0
ZTAeFw0yNDA2MjIwMjIzMDFaFw0yNDA2MjIxNDIzMDFaMAAwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAASxG6RZr3nWAycvZxnk7SQqU74MVPvXd4Is+8/2HZ9cefs1
9V0z6soj/fCe0law7tkaFjI0ghe5UenpRjZAcuFEo4GOMIGLMA4GA1UdDwEB/wQE
AwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFMT3
+W+u5LOTo2WWO91+iVn4w4NgMB8GA1UdIwQYMBaAFHQdqUm+o9r6kGBaZVPSfBJb
xGpBMBoGA1UdEQEB/wQQMA6CDG5hcmExNy5sb2NhbDAKBggqhkjOPQQDAgNHADBE
AiBY0PZeU0P9BYMwTjO0qtoygPJalS7Pgt3qbL+klHE+JQIgZmYc2osIM08lFHSZ
RI6pxytEIiEmwqegu6Xx/xmLveU=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIBozCCAUmgAwIBAgIQXMTJCGVZBuGDZkmX7VXsTjAKBggqhkjOPQQDAjAwMS4w
LAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDI1IEVDQyBSb290MB4X
DTI1MDMxMDExMjExNVoXDTM1MDExNzExMjExNVowMDEuMCwGA1UEAxMlQ2FkZHkg
TG9jYWwgQXV0aG9yaXR5IC0gMjAyNSBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABL1qj+/vcnQ9wOx/rvgC/QKn5BXL9iJxK6nf+Kze1UGmK8VJ7GQ/
X1ycPFPqTZl0FYx9E1iSef6v5m1CRIsxIcKjRTBDMA4GA1UdDwEB/wQEAwIBBjAS
BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTdhAY6FjWfce0PJmkjp1hfVki1
IzAKBggqhkjOPQQDAgNIADBFAiBimGSbTKcTI3sR3bDY+DnJRoZIsrf9X08TsuMe
Uzqa9wIhAOc/dHWVECv339x8jhPFnEYmgr8mbQ2ONRaSXEIdClWx
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICDDCCAbKgAwIBAgIQPcRqHxvC+Xphgq4om6a5ojAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTI1MDcxMzAzNDYyOFoXDTM1MDcxMzAzNDYyOFowZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABMaZs5p1mAuRFl4JtdbUwJeFKPA0bNQevikO
e2HlE4H3FuVz/JU08cMggZhCF7LfmD51Oh9zXfaGT/0FabyEmFejQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSKjYQTgAg6UjWT
Ft8avIH7O8sR6zAKBggqhkjOPQQDAgNIADBFAiBc/4AuP8zZgJu7piOzxRWY2w/2
Syif7P27trOX9CmJFQIhAI6Ha6S2RoifhZ7erozvsW4wtbtbpIlFKSdhdy0uAk8m
-----END CERTIFICATE-----

    ''
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.05"; # Did you read the comment?
}
